---
title: "R Notebook"
output: html_notebook
---

---
title: "R Notebook"
output: html_notebook
---

```{r}
library(imager)
help(package="imager")
```

```{r}
# getwd()
# list.files("..")
# fil <- "../ANG242_2021_10_22_20x_Well_1_Field_5_BF.png"
fil <- "ANG242_2021_10_22_20x_Well_1_Field_5_GFP.png"
# file.exists(fil)
pic <- imager::load.image(fil)
plot(pic, rescale = FALSE)
```

## Draw a filled rectangle:
```{r}
# dim(pic) # 1936 1216
# class(pic) # "cimg"         "imager_array" "numeric"
height(pic) # 1216
width(pic) # 1936
# pic[1:10, 1:10]
pic2 <- pic
pic2[1:500, 1:500, 1, 1] <- 1
x <- 1
pic2[x:500, 1:500, 1, 1] <- 1
plot(pic2)
```


## Draw a rectangular frame by editing matrix
```{r}
my.draw.rect <- function(img, x.left, x.right, y.top, y.bottom, stroke=3) {
  # img[x.left:x.right, y.top:y.top+stroke-1] <- 1
  tmp <- img
  tmp[x.left:x.right, y.top:(y.top+stroke-1), 1, 1] <- 1
  tmp[x.left:x.right, (y.bottom-stroke+1):y.bottom, 1, 1] <- 1
  tmp[x.left:(x.left+stroke-1), y.top:y.bottom, 1, 1] <- 1
  tmp[(x.right-stroke+1):x.right, y.top:y.bottom, 1, 1] <- 1
  tmp
}
system.time({
  x <- my.draw.rect(pic, x.left=50, x.right=1000, y.top=200, y.bottom=800, stroke=10)
}) # 0.323
```


Draw filled rectangle using `imager::draw_rect()`

```{r}
pic2 <- add.colour(pic)
class(pic) # "cimg"         "imager_array" "numeric"
typeof(pic) # "double"
spectrum(pic) # 1
dim(pic) # 1936 1216    1    1
class(pic2) # "cimg"         "imager_array" "numeric"
typeof(pic2) # "double"
spectrum(pic2) # 3
dim(pic2) # 1936 1216    1    3
plot(pic2)
```


```{r}
# draw_rect
# spectrum(pic2)
# system.time({
#   pic3 <- imager::draw_rect(pic2, 100, 100, 300, 300, "red", filled=TRUE, opacity = 1)
# }) # 0.624
pic3 <- imager::draw_rect(pic2, 1, 1, 300, 1, "red", filled=TRUE, opacity = 1)
# Setting filled=FALSE draws nothing
plot(pic3)
```

```{r}
class(pic3) # "cimg"         "imager_array" "numeric" 
str(pic3)
# 'cimg' num [1:1936, 1:1216, 1, 1:3] 0.302 0.294 0.29 0.302 0.306 ...
dim(pic3) # 1936 1216    1    3
range(pic3) # 0 1
spectrum(pic3) # 3
range(pic3[,,1,1]) # 0.2470588 1.0000000
range(pic3[,,1,2]) # 0.0000000 0.7254902
range(pic3[,,1,3]) # 0.0000000 0.7254902
```

```{r}
which(pic3[,,1,1] > 0) %>% head
which(pic3[,,1,2] > 0) %>% head
which(pic3[,,1,1] > 0) %>% head
dim(pic3[,,1,1]) # 1936 1216
pic3[1:4,1:4,1,1]
```



```{r}
# Grayscale image in RGB format:
pic4 <- pic2
# plot(pic4)
pic4[1:300, 100:120, 1, 1] <- 1
plot(pic4)
```

```{r}
my.draw.rect2 <- function(img, x.top.left, y.top.left, width, stroke=5) {
  # img[x.left:x.right, y.top:y.top+stroke-1] <- 1
  stopifnot(imager::spectrum(img) == 3)
  tmp <- img
  # Horizontal line top:
  tmp[x.top.left:(x.top.left+width-1), y.top.left:(y.top.left+stroke-1), 1, 1] <- 1
  # Horizontal line bottom:
  tmp[x.top.left:(x.top.left+width-1), (y.top.left+width-stroke+1):(y.top.left+width), 1, 1] <- 1
  # Vertical line left:
  tmp[x.top.left:(x.top.left+stroke-1), y.top.left:(y.top.left+width-1), 1, 1] <- 1
  # Vertical line right:
  tmp[(x.top.left+width-stroke+1):(x.top.left+width-1), y.top.left:(y.top.left+width-1), 1, 1] <- 1
  tmp
}
x <- my.draw.rect2(pic2, 500, 200, 500, 20)
plot(x)
```

